store/src/main/java/com/dropbox/android/external/store4/StoreBuilder.kt
store/src/main/java/com/dropbox/android/external/store4/StoreRequest.kt
store/src/main/java/com/dropbox/android/external/store4/StoreResponse.kt
store/src/main/java/com/dropbox/android/external/store4/impl/FetcherController.kt
store/src/main/java/com/dropbox/android/external/store4/impl/RealStore.kt
store/src/main/java/com/dropbox/android/external/store4/impl/RefCountedResource.kt
store/src/main/java/com/dropbox/android/external/store4/impl/SourceOfTruth.kt
store/src/main/java/com/dropbox/android/external/store4/impl/SourceOfTruthWithBarrier.kt
store/src/main/java/com/dropbox/android/external/store4/impl/multicast/ChannelManager.kt
store/src/main/java/com/dropbox/android/external/store4/impl/multicast/Multicaster.kt
store/src/main/java/com/dropbox/android/external/store4/impl/multicast/SharedFlowProducer.kt
store/src/main/java/com/dropbox/android/external/store4/impl/multicast/StoreRealActor.kt
store/src/main/java/com/dropbox/android/external/store4/impl/operators/FlowMerge.kt
store/src/main/java/com/dropbox/android/external/store4/impl/operators/MapIndexed.kt
store/src/test/java/com/dropbox/android/external/store3/TestStoreBuilder.kt
store/src/test/java/com/dropbox/android/external/store4/FetcherControllerTest.kt
store/src/test/java/com/dropbox/android/external/store4/SourceOfTruthWithBarrierTest.kt
store/src/test/java/com/dropbox/android/external/store4/impl/FakeFetcher.kt
store/src/test/java/com/dropbox/android/external/store4/impl/FlowStoreTest.kt
store/src/test/java/com/dropbox/android/external/store4/impl/FlowTestExt.kt
store/src/test/java/com/dropbox/android/external/store4/impl/KeyTrackerTest.kt
store/src/test/java/com/dropbox/android/external/store4/impl/SimplePersisterAsFlowable.kt
store/src/test/java/com/dropbox/android/external/store4/impl/SimplePersisterAsFlowableTest.kt
store/src/test/java/com/dropbox/android/external/store4/impl/StreamWithoutSourceOfTruthTest.kt
store/src/test/java/com/dropbox/android/external/store4/impl/multicast/ChannelManagerTest.kt
store/src/test/java/com/dropbox/android/external/store4/impl/multicast/InfiniteMulticastTest.kt
store/src/test/java/com/dropbox/android/external/store4/impl/multicast/MulticastTest.kt
store/src/test/java/com/dropbox/android/external/store4/impl/multicast/StoreRealActorTest.kt

this adds Google copyright to the files created by Google employees.

add missing google copyright header

---

README.md

Add how to build from source and install into local m2 repo

Add note about missing maven artifact

---

build.gradle
multicast/build.gradle
multicast/gradle.properties
multicast/src/main/kotlin/com/dropbox/flow/multicast/ChannelManager.kt
multicast/src/main/kotlin/com/dropbox/flow/multicast/Multicaster.kt
multicast/src/main/kotlin/com/dropbox/flow/multicast/SharedFlowProducer.kt
multicast/src/main/kotlin/com/dropbox/flow/multicast/StoreRealActor.kt
multicast/src/test/kotlin/com/dropbox/flow/multicast/ChannelManagerTest.kt
multicast/src/test/kotlin/com/dropbox/flow/multicast/InfiniteMulticastTest.kt
multicast/src/test/kotlin/com/dropbox/flow/multicast/MulticastTest.kt
multicast/src/test/kotlin/com/dropbox/flow/multicast/StoreRealActorTest.kt
settings.gradle
store/build.gradle
store/src/main/java/com/dropbox/android/external/store4/impl/FetcherController.kt

cmove multicast to its own module

---

store/src/main/java/com/dropbox/android/external/store4/Store.kt
store/src/main/java/com/dropbox/android/external/store4/StoreBuilder.kt
store/src/test/java/com/dropbox/android/external/store3/TestStoreBuilder.kt

Some cleanup of `StoreBuilder`. Most notably do not expose `Builder` which was made private and  renamed `BuilderImpl`.
Also add some documentation to `StoreBuilder`

Cleanup StoreBuilder interface and add some documentation

---

app/build.gradle
buildsystem/dependencies.gradle
filesystem/build.gradle
filesystem/src/test/java/com/dropbox/android/external/fs3/FSAllOperationTest.kt
filesystem/src/test/java/com/dropbox/android/external/fs3/FilePersisterTest.kt
filesystem/src/test/java/com/dropbox/android/external/fs3/FileSystemRecordPersisterTest.kt
filesystem/src/test/java/com/dropbox/android/external/fs3/MultiTest.kt
filesystem/src/test/java/com/dropbox/android/external/fs3/RecordPersisterTest.kt
filesystem/src/test/java/com/dropbox/android/external/fs3/SourcePersisterTest.kt
filesystem/src/test/java/com/dropbox/android/external/fs3/UtilTest.kt
filesystem/src/test/java/com/dropbox/android/external/fs3/filesystem/BreadthFirstFileTreeIteratorTest.kt
filesystem/src/test/java/com/dropbox/android/external/fs3/impl/SimpleTest.kt
multicast/build.gradle
multicast/src/test/kotlin/com/dropbox/flow/multicast/ChannelManagerTest.kt
multicast/src/test/kotlin/com/dropbox/flow/multicast/InfiniteMulticastTest.kt
multicast/src/test/kotlin/com/dropbox/flow/multicast/MulticastTest.kt
multicast/src/test/kotlin/com/dropbox/flow/multicast/StoreRealActorTest.kt

Migrate the rest of the modules to Truth and remove AssertJ dependency from the entire project.
#21

Migrate truth part 2

---

multicast/src/main/kotlin/com/dropbox/flow/multicast/ChannelManager.kt
multicast/src/test/kotlin/com/dropbox/flow/multicast/MulticastTest.kt

This PR changes the behavior of channel manager such that we unblock the upstream when a downstream arrives if and only if buffer is disabled.
This behavior change ensures that we'll not block a new downstream for values it will never receive

unblock upstream when a new downstream arrives

---

README.md

Hi, there. I knew this project via Twitter and now I'm so interested in it.
I will get familiarize myself with Store and let me open a tiny PR which aligns sample code.
Thank you for publishing this library anyway!

Refactor README sample code

---

README.md

Update README to reflect availability of alpha artifacts in Maven

---

store/src/main/java/com/dropbox/android/external/store4/MemoryPolicy.kt

added docs as requested in #67 

added docs to MemoryPolicy.setMemorySize

---

cache/README.md

`README.md` for the new cache implementation. Please let me know if there's anything else I should cover.

Add README.md for new cache module.

---

README.md

* Move "current version" to above maven coordinate
* Update docs for convenience `Store.get` and `Store.fresh` extensions
* Add a section on how to configure in-memory cache.

Improve README.md.

---

app/src/main/java/com/dropbox/android/sample/Graph.kt

Fix a bug where nothing was written to the buffer

Fix bug where RedditConfig was not persisted properly

---

store-rx2/build.gradle
store-rx2/src/main/kotlin/com/dropbox/store/rx2/RxStore.kt
store-rx2/src/test/kotlin/com/dropbox/store/rx2/test/HotRxSingleStoreTest.kt
store-rx2/src/test/kotlin/com/dropbox/store/rx2/test/RxFlowableStoreTest.kt
store-rx2/src/test/kotlin/com/dropbox/store/rx2/test/RxSingleStoreTest.kt

Fix kotlin compiler warnings in store-rx2 module.

---

CHANGELOG.md
README.md
build.gradle

Sonatype didn't like the artifacts, will try again after the weekend.

Revert the version bump

---

README.md

Use double quotes for string interpolation

Fix dependency declaration in README

---

CHANGELOG.md
README.md
build.gradle

Prepare for release 4.0.0-alpha04

---

buildsystem/dependencies.gradle
multicast/build.gradle
multicast/src/test/kotlin/com/dropbox/flow/multicast/ChannelManagerTest.kt
multicast/src/test/kotlin/com/dropbox/flow/multicast/InfiniteMulticastTest.kt
multicast/src/test/kotlin/com/dropbox/flow/multicast/MulticastTest.kt
multicast/src/test/kotlin/com/dropbox/flow/multicast/SharedFlowProducerTest.kt
multicast/src/test/kotlin/com/dropbox/flow/multicast/StoreRealActorTest.kt

To be able to move tests to commonTest later

Migrate Multicast to Kotlin Test

---

filesystem/src/main/java/com/dropbox/android/external/fs3/Util.kt
filesystem/src/main/java/com/dropbox/android/external/fs3/filesystem/BreadthFirstFileTreeIterator.kt
filesystem/src/main/java/com/dropbox/android/external/fs3/filesystem/FileSystemImpl.kt

Remove unneeded java.util packages. Not really solves #127 but helps a little :D

Remove some unneeded java.util packages

---

build.gradle

This is a release PR, it must be merged as individual commits. Do not squash commits on merge

Prepare for release 4.0.0-alpha07

---

gradle/maven-push.gradle
tools/release/deploy_snapshot.sh

Not sure why the in memory pgp method isn't working. 
Tested sign archives locally and it's not being skipped anymore

Update signing method

---

app/src/main/java/com/dropbox/android/sample/MainActivity.kt
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/fragment_room_store.xml

After checking out the sample app to get to know the project, I found some small improvements.

Sample app improvements

---

CHANGELOG.md
README.md
build.gradle

Prepare for release 4.0.0

---

build.gradle

Prepare for release 4.0.1

---

build.gradle

Prepare next development version.

---

app/build.gradle
buildsystem/dependencies.gradle

Bumping to 4.0.1 and updating to use Maven coordinates instead of project.

Bump dependencies for sample app

---

CHANGELOG.md
README.md
build.gradle

Preparing for release of Kotlin 1.5 compat version.
Closes #263

Prepare for release 4.0.2-KT15

---

buildsystem/dependencies.gradle
store/src/test/java/com/dropbox/android/external/store3/StreamOneKeyTest.kt

This is just a version bump, we still need to followup
with cleanup.
Test: ./gradlew check

Update kotlin to 1.5.21, coroutines to 1.5

---

.github/dependabot.yml

Add dependabot for Store

---

app/build.gradle

Looks like this app finally went over the limit.
I signed the CLA and read the doc: https://opensource.dropbox.com/cla/

Update sample app to support multidex

---

gradle.properties

Same fix as https://github.com/dropbox/kaiken/pull/70

Increase memory for dokka

---

CHANGELOG.md
README.md
RELEASING.md
gradle.properties

Prepare for release 4.0.4-KT15

---

.github/workflows/.ci_test_and_publish.yml

Update git actor for auto commit

---

gradle.properties

Prepare next development version

---

.github/workflows/.ci_test_and_publish.yml

Removing this for the same reason as https://github.com/dropbox/Store/pull/365#issuecomment-989310094

Remove action to update version

---

buildsystem/dependencies.gradle

Upgrades Room.  Fixes M1 Support as well.
Related PRs and Issues:
* #409
* #410

Room 2.4.2 Upgrade

---

CHANGELOG.md
README.md
buildsystem/dependencies.gradle

Update sample app to use latest stable version 4.0.5.

Update CHANGELOG and Sample App to use 4.0.5.

---

build.gradle
buildsystem/dependencies.gradle
cache/build.gradle
filesystem/build.gradle
multicast/build.gradle
store-rx2/build.gradle
store-rx3/build.gradle
store/build.gradle

Bump Maven publish plugin

---

.github/workflows/.ci_test_and_publish.yml
.github/workflows/create_swift_package.yml
buildSrc/src/main/kotlin/Version.kt
gradle.properties
store/build.gradle.kts
store/gradle.properties

Update CI and autogenerate Swift Package

---

.github/workflows/create_swift_package.yml
build.gradle
buildSrc/src/main/kotlin/Deps.kt
buildSrc/src/main/kotlin/Version.kt
samples/notes/android/app/build.gradle.kts
samples/notes/android/common/scoping/build.gradle.kts
samples/notes/android/feature/account/build.gradle.kts
samples/notes/android/feature/explore/build.gradle.kts
samples/notes/android/feature/home/build.gradle.kts
samples/notes/android/lib/navigation/build.gradle.kts
store/build.gradle.kts
store/store.podspec

Use KMM Bridge

---

store/build.gradle.kts

Fix Maven publish plugin

---

CHANGELOG.md
README.md
RELEASING.md
gradle.properties
store/build.gradle.kts

Prepare for release 5.0.0-alpha1

---

gradle.properties

Prepare for next development version

---

.github/workflows/create_swift_package.yml

Only generate Swift Package on release

---

store/build.gradle.kts
store/src/commonTest/kotlin/com/dropbox/external/store5/ItemValidatorTests.kt
store/src/commonTest/kotlin/com/dropbox/external/store5/MarketTests.kt
store/src/commonTest/kotlin/com/dropbox/external/store5/MemoryLruStoreTests.kt
store/src/commonTest/kotlin/com/dropbox/external/store5/OfflineMarketTests.kt
store/store.podspec

Target browser and Node!

---

store/build.gradle.kts
store/src/commonTest/kotlin/com/dropbox/external/store5/ItemValidatorTests.kt
store/src/commonTest/kotlin/com/dropbox/external/store5/MarketTests.kt
store/src/commonTest/kotlin/com/dropbox/external/store5/MemoryLruStoreTests.kt
store/src/commonTest/kotlin/com/dropbox/external/store5/OfflineMarketTests.kt
store/store.podspec

Matt ramotar/store5/ios

---

.github/workflows/.ci_test_and_publish.yml

Run CI on MacOS

---

.github/workflows/create_swift_package.yml
CHANGELOG.md
README.md
RELEASING.md
gradle.properties
store/build.gradle.kts

Signed-off-by: Matt Ramotar <mramotar@dropbox.com>

Prepare for release 5.0.0-alpha02

---

.github/workflows/create_swift_package.yml
CHANGELOG.md
gradle.properties

Signed-off-by: Matt Ramotar <mramotar@dropbox.com>

Release 5.0.0-alpha03

---

.github/workflows/create_swift_package.yml
gradle.properties

Prepare for Development

---

build.gradle.kts
buildSrc/src/main/kotlin/Deps.kt
buildSrc/src/main/kotlin/Version.kt
cache/build.gradle.kts
multicast/build.gradle.kts
store/build.gradle.kts

Expose AtomicFU

---

.github/workflows/check.yml

See https://github.com/MobileNativeFoundation/Store/pull/516#issuecomment-1431662417

Modify workflow

---

.github/workflows/.ci_test_and_publish.yml

Fix wrong git head referenced in PR workflow

---

store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/StoreBuilder.kt
store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/impl/RealMutableStore.kt
store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/impl/RealStoreBuilder.kt
store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/impl/extensions/store.kt

Make bookkeeper optional

---

cache/build.gradle.kts
multicast/build.gradle.kts
store/build.gradle.kts

Target linuxX64

---

.github/ISSUE_TEMPLATE/proposal.md

See https://github.com/golang/proposal/blob/master/design/TEMPLATE.md

Add Proposal Template

---

store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/StoreReadRequest.kt
store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/impl/RealStore.kt

Incorporate @tsenggordon comments from #545

Tweak fallback implementation

---

CHANGELOG.md
README.md
buildSrc/src/main/kotlin/Version.kt
gradle.properties

Release 5.0.0-alpha06

---

store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/MutableStoreBuilder.kt
store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/SourceOfTruth.kt
store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/impl/RealMutableStoreBuilder.kt
store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/impl/RealSourceOfTruth.kt
store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/impl/RealStore.kt
store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/impl/SourceOfTruthWithBarrier.kt
store/src/commonTest/kotlin/org/mobilenativefoundation/store/store5/UpdaterTests.kt

- Generic
- Formatting
- Comment out UpdaterTests

Passing except for UpdaterTests

---

store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/impl/RealStore.kt
store/src/commonTest/kotlin/org/mobilenativefoundation/store/store5/UpdaterTests.kt
store/src/commonTest/kotlin/org/mobilenativefoundation/store/store5/util/fake/NotesValidator.kt

Fixes #571 sorry for the terrible dev practices everyone

fix validator

---

CHANGELOG.md
README.md
gradle.properties

Prepare for release 5.0.0-beta03

---

CHANGELOG.md
README.md
gradle.properties

Prepare for release 5.0.0

---

README.md
build.gradle.kts
core/src/commonMain/kotlin/org/mobilenativefoundation/store/core5/ExperimentalStoreApi.kt
core/src/commonMain/kotlin/org/mobilenativefoundation/store/core5/InsertionStrategy.kt
core/src/commonMain/kotlin/org/mobilenativefoundation/store/core5/KeyProvider.kt
core/src/commonMain/kotlin/org/mobilenativefoundation/store/core5/StoreData.kt
core/src/commonMain/kotlin/org/mobilenativefoundation/store/core5/StoreKey.kt
gradle.properties
paging/build.gradle.kts
paging/src/commonMain/kotlin/org/mobilenativefoundation/store/paging5/LaunchPagingStore.kt
paging/src/commonTest/kotlin/org/mobilenativefoundation/store/paging5/LaunchPagingStoreTests.kt
paging/src/commonTest/kotlin/org/mobilenativefoundation/store/paging5/util/PostStoreFactory.kt
rx2/src/main/kotlin/org/mobilenativefoundation/store/rx2/RxStore.kt
rx2/src/test/kotlin/org/mobilenativefoundation/store/rx2/test/RxSingleStoreExtensionsTest.kt
rx2/src/test/kotlin/org/mobilenativefoundation/store/rx2/test/RxSingleStoreTest.kt
store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/Clear.kt
store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/MutableStore.kt
store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/StoreBuilder.kt
store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/Write.kt
store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/impl/RealMutableStore.kt
store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/impl/RealStore.kt
store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/impl/RealStoreBuilder.kt
store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/impl/extensions/store.kt
store/src/commonTest/kotlin/org/mobilenativefoundation/store/store5/ClearAllStoreTests.kt
store/src/commonTest/kotlin/org/mobilenativefoundation/store/store5/FetcherResponseTests.kt
store/src/commonTest/kotlin/org/mobilenativefoundation/store/store5/UpdaterTests.kt

Releasing 5.1.0-alpha01.
N/A
N/A

Release 5.1.0-alpha01

---

README.md
gradle.properties
gradle/libs.versions.toml
paging/src/commonTest/kotlin/org/mobilenativefoundation/store/paging5/LaunchPagingStoreTests.kt

Closes #599 
Releasing 5.1.0-alpha02
N/A
N/A
N/A

Release 5.1.0-alpha02

---

paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/PagingData.kt
paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/PagingKey.kt

Introducing `PagingKey` and `PagingData` to represent the key and data associated with each page of paged data.

Implement PagingKey and PagingData

---

paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/impl/QueueManager.kt
paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/impl/RealQueueManager.kt

- Defining `QueueManager`, responsible for managing the queue of pages to be loaded
- Implementing `RealQueueManager`, the concrete impl of `QueueManager`

Define QueueManager and Implement RealQueueManager

---

paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/UserCustomActionReducer.kt
paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/impl/DefaultReducer.kt
paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/impl/JobCoordinator.kt
paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/impl/RealJobCoordinator.kt
paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/impl/RetriesManager.kt

- Implementing the `DefaultReducer`

Implement DefaultReducer

---

paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/impl/RealPager.kt

Implement RealPager

---

README.md
gradle.properties
gradle/libs.versions.toml
tooling/plugins/src/main/kotlin/org/mobilenativefoundation/store/tooling/plugins/KotlinMultiplatformConventionPlugin.kt

Release 5.1.0-alpha03

---

store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/impl/RealStore.kt

Minor Typo Fix in RealStore.kt

Typo fix RealStore.kt

---

docs/mutable-store/building/implementations/bookkeeper.md

Fix docs to reflect the Bookkeeper's correct signature.

Fix Bookkeeper docs.
