app/build.gradle, app/src/main/java/com/dropbox/android/sample/Graph.kt, app/src/main/java/com/dropbox/android/sample/data/remote/Api.kt
The sample app is using the deprecated Retrofit coroutine adapter with Deferred.
It is advised to migrate to Retrofit's built-in suspend support.
More details at https://github.com/JakeWharton/retrofit2-kotlin-coroutines-adapter
=> Replace Retrofit's deprecated Deferred CallAdapter with its built-in suspend support.

README.md
The artifact id `store4`, so the current included example dependency line doesn't locate the library.   Changing it to `store4` correctly finds the library in the local repository.
=> Update Readme.md with correct artifact id

multicast/src/main/kotlin/com/dropbox/flow/multicast/Multicaster.kt, multicast/src/test/kotlin/com/dropbox/flow/multicast/InfiniteMulticastTest.kt, multicast/src/test/kotlin/com/dropbox/flow/multicast/MulticastTest.kt, store/src/main/java/com/dropbox/android/external/store4/impl/FetcherController.kt
Multicast implementation had a bug where the returned flow could
not be collected multiple times as it was using the same channel
it created when  was called.
This PR changes it to create per collection to avoid this issue.
I've also replaced  function with a  field as there
is no reason to keep creating a new one, it can be just a flow
Test: MultiplexTest#multipleCollections
Fixes: #26
=> Fix multiple collections on Multicast

buildsystem/dependencies.gradle, store/build.gradle, store/src/test/java/com/dropbox/android/external/store3/ClearStoreMemoryTest.kt, store/src/test/java/com/dropbox/android/external/store3/ClearStoreTest.kt, store/src/test/java/com/dropbox/android/external/store3/NoNetworkTest.kt, store/src/test/java/com/dropbox/android/external/store3/SequentialTest.kt, store/src/test/java/com/dropbox/android/external/store3/StoreTest.kt, store/src/test/java/com/dropbox/android/external/store3/StoreThrowOnNoItems.kt, store/src/test/java/com/dropbox/android/external/store3/StreamOneKeyTest.kt, store/src/test/java/com/dropbox/android/external/store3/base/impl/MemoryPolicyBuilderTest.kt, store/src/test/java/com/dropbox/android/external/store4/FetcherControllerTest.kt, store/src/test/java/com/dropbox/android/external/store4/SourceOfTruthWithBarrierTest.kt, store/src/test/java/com/dropbox/android/external/store4/impl/FakeFetcher.kt, store/src/test/java/com/dropbox/android/external/store4/impl/FlowTestExt.kt, store/src/test/java/com/dropbox/android/external/store4/impl/KeyTrackerTest.kt, store/src/test/java/com/dropbox/android/external/store4/impl/SimplePersisterAsFlowableTest.kt, store/src/test/java/com/dropbox/android/external/store4/impl/StreamWithoutSourceOfTruthTest.kt
As discussed in issue #21, this PR is to implement Truth and migrate the store module's tests. 
To allow a smooth transition and get some feedback first I just converted the tests in the store module and removed AssertJ from store module's dependencies as part of this PR. Next steps would be converting the rest of the modules and removing AssertJ library from the codebase.
=> Implement Truth and migrate store module

multicast/src/main/kotlin/com/dropbox/flow/multicast/ChannelManager.kt, multicast/src/main/kotlin/com/dropbox/flow/multicast/Multicaster.kt, multicast/src/main/kotlin/com/dropbox/flow/multicast/SharedFlowProducer.kt, multicast/src/test/kotlin/com/dropbox/flow/multicast/ChannelManagerLegacyTest.kt, multicast/src/test/kotlin/com/dropbox/flow/multicast/ChannelManagerTest.kt, multicast/src/test/kotlin/com/dropbox/flow/multicast/InfiniteMulticastTest.kt, multicast/src/test/kotlin/com/dropbox/flow/multicast/MulticastTest.kt, store/src/main/java/com/dropbox/android/external/store4/impl/FetcherController.kt
Main changes:
* ~`ChannelManager` no longer inherits from `StoreRealActor` but rather delegates to one~ (will send in a separate PR).
* messages coming from the upstream were placed under `Message.Dispach` rather than `Message`. These are the only messages accepted from outside`ChannelManager`
* `ChannelManager` now only exposes `plusAsign`, `minusAsign` for adding/removing channels, close for closing  and send(msg, Message.Dispatch) for upstream events
* `SharedFlowProducer` no longer has a back dependency on `ChannelManager`, rather it accepts a `suspend (Message.Dispatch) -> Unit`
* `ChannelManager` is now built with the upstream flow rather than a flow factory. Given that a flow is stateless, passing in a flow that can be re-consumed seems like the simpler API.
* New `ChannelManager` …
=> Clean up ChannelManager's interface to make it easier to add more tests (and add some)

multicast/src/main/kotlin/com/dropbox/flow/multicast/Multicaster.kt, multicast/src/main/kotlin/com/dropbox/flow/multicast/StoreRealActor.kt, multicast/src/test/kotlin/com/dropbox/flow/multicast/ChannelManagerTest.kt, multicast/src/test/kotlin/com/dropbox/flow/multicast/MulticastTest.kt
This PR defines the behavior of Multicast Flow.
Previously, it could crash if new observers are added to the
multicaster or if it is closed while there is an active
collector. Now, both of these operations complete without
an error. Collecting on a closed multicaster receives 0
values and closes immediately.
Fixes: #45
Test: ChannelManagerTest, MulticastTest
=> Properly implement multicast closing

README.md
There is no method `fetch()` in Store API, therefore information in ReadMe seemed to be confusing
=> Replace Store.fetch() on fresh() methods in ReadMe

cache/gradle.properties, filesystem/gradle.properties, store/gradle.properties
`store`, `cache` and `filesystem` are all pure JVM / Kotlin modules with no Android dependencies. This PR changes the `POM_PACKAGING` from `aar` to `jar` for these modules (`multicast` module is already packaging `jar`).
=> Switch POM packaging format to jar for cache, filesystem and store modules.

build.gradle, gradle/wrapper/gradle-wrapper.properties, store/build.gradle, store/src/main/java/com/dropbox/android/external/store4/DiskRead.kt, store/src/main/java/com/dropbox/android/external/store4/DiskWrite.kt, store/src/main/java/com/dropbox/android/external/store4/MemoryPolicy.kt, store/src/main/java/com/dropbox/android/external/store4/Persister.kt, store/src/main/java/com/dropbox/android/external/store4/Store.kt, store/src/main/java/com/dropbox/android/external/store4/StoreBuilder.kt, store/src/main/java/com/dropbox/android/external/store4/StoreRequest.kt, store/src/main/java/com/dropbox/android/external/store4/legacy/BarCode.kt
Tomorrow (January 8th) we will releasing the first alpha along with a blog post. This is some general cleanup to get our 🦆s in a row
* Fix dokka configuration and default to javadoc style report
* Refine comments
* Add a new override to `StoreBuilder` for legacy `Persister`
=> fix dokka, update comments, integrate persister

CHANGELOG.md, README.md, build.gradle
First commit bumps version to 4.0.0-alpha01. I staged the artifact on Sonatype with this version. Next commit just bumps version to next development version 4.0.0-alpha02-SNAPSHOT.
=> Increment version for 4.0.0-alpha01 release and prep next development version

store/src/main/java/com/dropbox/android/external/store4/StoreResponse.kt, store/src/main/java/com/dropbox/android/external/store4/impl/RealStore.kt
By calling `StoreResponse.swapType` always on when creating a network flow we were always casting `Input` type to `Output`.
When there's no `sourceOfTruth` this isn't a problem as `Input == Output`
Where there's a `sourceOfTruth` then we do an illegal cast (which doesn't crash due to type erasure) then we avoid actually crashing (by attempting to access an instance of `Input` as an `Output` object) because we filter out  inside `networkFlow.merge(diskFlow)`
While this currently does not crash it's pretty easy to see code changes in the future exposing the illegally casted network element and trying to access it (e.g logging).
Change `createNetworkFlow` to return the correct type `Flow<StoreResponse<Input>>` and perform the typecasting when actually using the return type to fix this
=> Avoid illegal cast in RealStore.stream

store/src/main/java/com/dropbox/android/external/store4/MemoryPolicy.kt, store/src/test/java/com/dropbox/android/external/store3/base/impl/MemoryPolicyBuilderTest.kt
Per the recently added docs for `MemoryPolicy.setMemorySize(maxSize: Long): MemoryPolicyBuilder`, when `setMemorySize` is not called, the cache size should be unlimited.
However currently the `maxSize` is automatically set to `1` with the default builder.
```kotlin
val policy = MemoryPolicy.builder().build() // maxSize is 1
```
This PR fixes this inconsistency with `Cache.Builder` by leaving the `maxSize` to `DEFAULT_POLICY` (-1) if not set explicitly.
=> Fix default MemoryPolicy.

store/src/test/java/com/dropbox/android/external/store4/impl/FlowStoreTest.kt, store/src/test/java/com/dropbox/android/external/store4/impl/FlowSubjectTest.kt, store/src/test/java/com/dropbox/android/external/store4/impl/FlowTestExt.kt, store/src/test/java/com/dropbox/android/external/store4/impl/StreamWithoutSourceOfTruthTest.kt
This PR changes the assertItems util method in tests to drain the
flow to ensure we don't produce unwated items.
=> Change flow collection util to drain the flow

multicast/src/main/kotlin/com/dropbox/flow/multicast/ChannelManager.kt, multicast/src/main/kotlin/com/dropbox/flow/multicast/Multicaster.kt, multicast/src/test/kotlin/com/dropbox/flow/multicast/InfiniteMulticastTest.kt, multicast/src/test/kotlin/com/dropbox/flow/multicast/MulticastTest.kt, store/src/main/java/com/dropbox/android/external/store4/impl/FetcherController.kt, store/src/main/java/com/dropbox/android/external/store4/impl/RealStore.kt, store/src/test/java/com/dropbox/android/external/store4/impl/FlowStoreTest.kt
multicaster already has the concept of piggyback only downstream - which are downstream that are carried over after an upstream was closed to be emitted by a following one. This pr updates the multicaster's API to allow to add a downstream at piggyback state directly and uses that in order to fix #59. This now allows us to "listen" to a fetcher without triggering a fetch when not needed.
=> introduce piggyback only downstreams to multicaster and fix #59

cache/src/main/kotlin/com/dropbox/android/external/cache4/RealCache.kt, cache/src/test/kotlin/com/dropbox/android/external/cache4/CacheEvictionTest.kt
Fixes #89.
PR fixes a `ConcurrentModificationException` during cache eviction due to iterating over the `accessQueue` when calling `accessQueue.first()` without synchronizing the `accessQueue` (MutableSet).
Manually verified that the exception is no longer thrown after pressing "REPEAT TEST" multiple times in the [sample app](https://github.com/atonamy/store4-issue).
=> Fix ConcurrentModificationException during Cache eviction

gradle/wrapper/gradle-wrapper.properties
@digitalbuddha Looks like people are finding this annoying after all 😅. Should we stick to the latest stable release for Gradle wrapper?
=> Fix gradle wrapper version.

CONTRIBUTING.md, build.gradle, cache/api/cache.api, filesystem/api/filesystem.api, multicast/api/multicast.api, store-rx2/api/store-rx2.api, store/api/store.api
This PR introduces the [binary-compatibility-validator plugin](https://github.com/Kotlin/binary-compatibility-validator) for tracking binary compatibility of our public APIs.
The plugin has 2 gradle tasks:
- `./gradlew apiDump` - generates the API dump files for the current public API. When we intend to make changes to the public API we need to run this command and commit the updated API dumps.
- `./gradlew apiCheck` - builds the projects and verifies that the current public APIs are consistent with the API dump files (baseline).  This is automatically added to the `check` task.
Resolves #96.
=> Start tracking API binary compatibility

gradle/wrapper/gradle-wrapper.properties
Don't understand why codecov broke on this, but a git bisect pointed to updating the wrapper to 6.1.1 to be the culprit.
Test Plan: Code Cov posts to this PR.
=> Fix CodeCov by changing gradle-wrapper to 6.1

store-rx2/src/test/kotlin/com/dropbox/store/rx2/test/RxSingleStoreTest.kt, store/src/main/java/com/dropbox/android/external/store4/impl/RealStore.kt
This PR fixes a bug in the ordering where if disk is skipped and network
is super fast, there is a tiny chance that we wouldn't latch onto source
of truth before triggering network and that would make SourceOfTruth think
that the value was written to disk before it observed, hence become a disk
value rather than fetcher.
This PR ensures that we unlock the network only after we establish a position
in the disk read queue so that we'll know the fetcher value came afterwards.
Fixes: #114
Test: RxSingleStoreTest
=> Ensure network starts after disk is established

gradle/wrapper/gradle-wrapper.properties, store-rx2/src/test/kotlin/com/dropbox/store/rx2/test/RxSingleStoreTest.kt
Let's see if this still breaks codecov.
=> Gradle 6.2.

store-rx2/src/main/kotlin/com/dropbox/store/rx2/RxStore.kt
Two small changes to the KDoc in RxStore. One to avoid confusion between Coroutine Flows and RxJava Flowables. The other to fix an IDE warning about not being able to find `persister` because it is a function in another class.
=> Fix typo in RxStore

multicast/src/main/kotlin/com/dropbox/flow/multicast/SharedFlowProducer.kt, multicast/src/test/kotlin/com/dropbox/flow/multicast/SharedFlowProducerTest.kt
This PR fixes a bug in SharedFlowProducer where it would not handle start being called
multiple times or cancel being called before start is completed. It could even consume
the upstream flow multiple times if start is called multiple times.
Fixes: #120
Test: SharedFlowProducerTest
=> Make SharedFlowProducer APIs safe

cache/api/cache.api, cache/src/main/kotlin/com/dropbox/android/external/cache4/Cache.kt, cache/src/main/kotlin/com/dropbox/android/external/cache4/RealCache.kt, cache/src/test/kotlin/com/dropbox/android/external/cache4/DefaultCacheTest.kt
The original Cache Java implementation had `asMap` function returning the Cache entries as a Map. Adding that feature back to Store 4.
=> Add `asMap` function to Cache for backward compat

cache/src/main/kotlin/com/dropbox/android/external/cache4/RealCache.kt, cache/src/test/kotlin/com/dropbox/android/external/cache4/DefaultCacheTest.kt
Remove unnecessary Collections.unmodifiableMap since we already return a defensive copy. Also write test to verify we returns a copy
=> Small: Remove Collections.unmodifiableMap

build.gradle
Pre-dex is really outdated and is no longer recommended to disable. The flag was not even used.
`gradlePluginPortal()` function is used. It adds the same maven url.
=> Some little Gradle clean-up

cache/src/main/kotlin/com/dropbox/android/external/cache4/RealCache.kt, cache/src/test/kotlin/com/dropbox/android/external/cache4/CacheEvictionTest.kt, store/src/test/java/com/dropbox/android/external/store4/impl/ConcurrentStoreRequestTest.kt, store/src/test/java/com/dropbox/android/external/store4/impl/StoreWithInMemoryCacheTest.kt
Fixes #152.
PR fixes a deadlock during cache eviction due to duplicate `CacheEntries` with different `accessTimeNanos` being added to the `accessQueue` HashSet.
`CacheEntry` should not have been a data class.
Added a cache eviction test and a higher level integration test in `store` module.
=> Fix a deadlock during cache eviction

app/src/main/java/com/dropbox/android/sample/SampleApp.kt, app/src/main/java/com/dropbox/android/sample/ui/room/RoomFragment.kt, buildsystem/dependencies.gradle, gradle/wrapper/gradle-wrapper.properties, multicast/build.gradle, multicast/src/main/kotlin/com/dropbox/flow/multicast/ChannelManager.kt, multicast/src/main/kotlin/com/dropbox/flow/multicast/Multicaster.kt, multicast/src/main/kotlin/com/dropbox/flow/multicast/SharedFlowProducer.kt, multicast/src/main/kotlin/com/dropbox/flow/multicast/StoreRealActor.kt, multicast/src/test/kotlin/com/dropbox/flow/multicast/ChannelManagerTest.kt, multicast/src/test/kotlin/com/dropbox/flow/multicast/InfiniteMulticastTest.kt, multicast/src/test/kotlin/com/dropbox/flow/multicast/MulticastTest.kt, multicast/src/test/kotlin/com/dropbox/flow/multicast/SharedFlowProducerTest.kt, multicast/src/test/kotlin/com/dropbox/flow/multicast/StoreRealActorTest.kt, store-rx2/src/main/kotlin/com/dropbox/store/rx2/RxFetcher.kt, store-rx2/src/main/kotlin/com/dropbox/store/rx2/RxSourceOfTruth.kt, store/src/main/java/com/dropbox/android/external/store4/Fetcher.kt, store/src/main/java/com/dropbox/android/external/store4/impl/operators/MapIndexed.kt
Update coroutines to 1.3.5 and clean up `@FlowPreview` and `@ExperimentalCoroutinesApi` which are no longer required.
Also updated kotlin sdtlib, Rx2, OkHttp, Okio and Gradle.
=> Coroutines 1.3.5

store/src/main/java/com/dropbox/android/external/store4/StoreBuilder.kt
I fixed the comment because StoreDefaults.cacheSize is 100.
(Sorry for the very small fix.)
=> fix doc: default policy of max items count

store/api/store.api, store/src/main/java/com/dropbox/android/external/store4/SourceOfTruth.kt, store/src/main/java/com/dropbox/android/external/store4/impl/RealStore.kt, store/src/main/java/com/dropbox/android/external/store4/impl/SourceOfTruthWithBarrier.kt, store/src/test/java/com/dropbox/android/external/store4/SourceOfTruthErrorsTest.kt, store/src/test/java/com/dropbox/android/external/store4/SourceOfTruthWithBarrierTest.kt, store/src/test/java/com/dropbox/android/external/store4/testutil/InMemoryPersister.kt
This PR fixes an issue where if SourceOfTruth's read or write method fails, we would just crash.
Now SourceOfTruth has two new exception types, WriteException and ReadException where each exception is sent to downstream as a `StoreResponse.Error.Exception` and stream is kept alive.
If a write fails, reader is simply restarted (because it was previously stopped to prepare for the write).
If a read fails, reader is not restarted until another write attempt happens. This is don't to avoid creating an infinite loop of trying to read from disk.
=> Emit source of truth errors to subscribers #177

cache/src/main/kotlin/com/dropbox/android/external/cache4/Cache.kt, store/src/main/java/com/dropbox/android/external/store4/MemoryPolicy.kt
It currently breaks consumers compiling with Kotlin 1.4-M3 (not sure why).
Added some TODOs to revert back to using Duration.INFINITE
once Store is compiled with Kotlin 1.4
Closes #188
=> Avoid using Duration.INFINITE

buildsystem/dependencies.gradle, gradle/wrapper/gradle-wrapper.properties, store/src/main/java/com/dropbox/android/external/store4/impl/RealStore.kt
Minor refactoring of RealStore.diskNetworkCombined to make it more readable:
- remove unused `withIndex`
- update comments
- 2 if-else -> 1 when
=> Minor cleanup in RealStore.diskNetworkCombined

store/src/main/java/com/dropbox/android/external/store4/SourceOfTruth.kt
Removed comment is already written in a paragraph before.
=> Remove duplicate comment

store/api/store.api, store/src/main/java/com/dropbox/android/external/store4/Store.kt, store/src/main/java/com/dropbox/android/external/store4/StoreRequest.kt, store/src/main/java/com/dropbox/android/external/store4/StoreResponse.kt, store/src/main/java/com/dropbox/android/external/store4/impl/FetcherController.kt, store/src/main/java/com/dropbox/android/external/store4/impl/RealStore.kt, store/src/test/java/com/dropbox/android/external/store3/StoreTest.kt, store/src/test/java/com/dropbox/android/external/store4/impl/FlowStoreTest.kt
solves #185 by adding no new data modeling
=> Add StoreResult.NoNewData for empty fetchers.

app/build.gradle, buildsystem/dependencies.gradle, cache/build.gradle, cache/src/main/kotlin/com/dropbox/android/external/cache4/Cache.kt, filesystem/build.gradle, multicast/build.gradle, multicast/src/main/kotlin/com/dropbox/flow/multicast/Multicaster.kt, store-rx2/build.gradle, store-rx3/build.gradle, store/api/store.api, store/build.gradle, store/src/main/java/com/dropbox/android/external/store4/impl/RealStore.kt, store/src/main/java/com/dropbox/android/external/store4/impl/SourceOfTruthWithBarrier.kt
I ran into the same [Duration issue](https://github.com/dropbox/Store/issues/188) after updating Kotlin to `1.4.0-rc` so here's a PR to update Store to compile with kotlin `1.4.0-rc` and revert @chrisbanes 's [workaround](https://github.com/dropbox/Store/issues/188) (tested snapshot artifact locally).
Also fixed a bunch of type inference issues raised by the new compiler.
Update:  just updated to kotlin `1.4.0` and Coroutines `1.3.9`.
=> Update to Kotlin 1.4.0, Coroutines 1.3.9 and revert to using Duration.INFINITE

CHANGELOG.md, README.md, build.gradle
This is a release PR, it must be merged as individual commits. Do not squash commits on merge.
=> Alpha07 release

tools/release/deploy_snapshot.sh
The deploy failed due to 
```
Unable to retrieve secret key from key ring file '/home/travis/build/dropbox/Store/cache/tools/release/secring.gpg' as it does not exist
```
https://travis-ci.org/github/dropbox/Store/builds/719455200?utm_source=github_status&utm_medium=notification
=> Use absolute path for signing key

buildsystem/dependencies.gradle, store/src/main/java/com/dropbox/android/external/store4/impl/SourceOfTruthWithBarrier.kt, store/src/test/java/com/dropbox/android/external/store4/SourceOfTruthWithBarrierTest.kt
This PR updates kotlin and coroutines versions and also removes the last usage of ConflatedBroadcastChannel.
=> update coroutines to 1.4.0, kotlin to 1.4.10

buildsystem/dependencies.gradle, filesystem/src/main/java/com/dropbox/android/external/fs3/filesystem/FileSystemImpl.kt, store/src/main/java/com/dropbox/android/external/store4/StoreDefaults.kt, store/src/main/java/com/dropbox/android/external/store4/impl/RealStore.kt
Fixes #263 
Unfortunately this is a breaking change. We need to release a new major version. I'll change to store5:5.0 after merge unless someone has a better idea
=> Remove deprecated code to fix error when users upgrade to kotlin 1.5 

.github/dependabot.yml
=> Configure Dependabot to only have 1 PR at a time and no major rev updates

buildsystem/dependencies.gradle, store-rx2/src/main/kotlin/com/dropbox/store/rx2/RxStoreBuilder.kt, store-rx3/src/main/kotlin/com/dropbox/store/rx3/RxStoreBuilder.kt
closes https://github.com/dropbox/Store/issues/207 by making comment align with the non rx store
=> Fix RxBuilder scheduler comment

cache/README.md
Added link to the Store Readme for the latest version to avoid duplication.
=> Fix cache artifact id and version

store/src/main/java/com/dropbox/android/external/store4/MemoryPolicy.kt
This should still maintain compatiblity with Kotlin 1.4 and 1.5 whilst also ensuring forward compatiblilty with Kotlin 1.6.
Compatibility with 1.4-M3 should be safe to drop.
Fixes #339
=> Revert to Duration.INFINITE

.github/workflows/.ci_test_and_publish.yml
=> Automatically prepare next development version

gradle/wrapper/gradle-wrapper.properties
Non-breaking Gradle Upgrade.  Things went crazy when I went straight to 7.4.1, so going conservative to 6.9.2.
=> Upgrade to Gradle 6.9.2 (Latest 6.x version)

.github/workflows/.ci_test_and_publish.yml
I wanted to see if we could pull this out into it's own PR instead of including in the larger version bumps PR: https://github.com/dropbox/Store/pull/414
=> Bumping CI to Java 11

app/build.gradle, app/src/main/java/com/dropbox/android/sample/MainActivity.kt, app/src/main/java/com/dropbox/android/sample/reddit/PostViewHolder.kt, app/src/main/java/com/dropbox/android/sample/ui/reddit/RedditFragment.kt, app/src/main/java/com/dropbox/android/sample/ui/room/RoomFragment.kt, app/src/main/java/com/dropbox/android/sample/ui/stream/StreamFragment.kt
Kotlin Android Extensions are deprecated, and must be removed before upgrading to AGP 7.
I manually tested the sample app to make sure it still works.
=> Remove Kotlin Android Extensions

.github/workflows/.ci_test_and_publish.yml, build.gradle, buildsystem/dependencies.gradle, gradle/wrapper/gradle-wrapper.properties, store/src/test/java/com/dropbox/android/external/store3/DontCacheErrorsTest.kt, store/src/test/java/com/dropbox/android/external/store3/NoNetworkTest.kt, store/src/test/java/com/dropbox/android/external/store3/SequentialTest.kt, store/src/test/java/com/dropbox/android/external/store3/StreamOneKeyTest.kt
I'm working my way to a Kotlin 1.6.10 upgrade.  These are safe version bumps to get us closer, but there are issues when bumping to higher versions of binary-compatibility-validator or the Kotlin Atomic FU plugin.  This gets us closer though so we can figure out the remaining issues to get to Kotlin 1.6.10
* AGP 4.1.0 -> 7.1.2
* Gradle Wrapper 6.9.2 -> 7.4.1
* Binary Compatibility Validator 0.2.3 -> 0.4.0
* Atomic Plugin 0.14.2 -> 0.15.1
* Kotlin 1.5.31 -> 1.6.10
* Android Build Tools 29.0.3 -> 30.0.3
* Spotless Plugin 3.26.1 -> 6.3.0
=> Version Bumps - AGP 7.1.2, Kotlin 1.6.10 and related updates

.github/workflows/.ci_test_and_publish.yml
We updated to Java 11 for the PR checks job https://github.com/dropbox/Store/pull/415 but we didn't do it for the publish job.  This fixes that.
=> Use Java 11 for Publish job

CHANGELOG.md, gradle.properties
Prepare for release 4.0.5
No code changes to the Store library.
Kotlin 1.6.10 dependency bump and updates to the sample application and build plugins.
This release contains [the following changes since `4.0.4-KT15`](https://github.com/dropbox/Store/compare/4.0.4-KT15...4.0.5)
=> Prepare for release 4.0.5

multicast/api/multicast.api, multicast/src/main/kotlin/com/dropbox/flow/multicast/ChannelManager.kt, multicast/src/main/kotlin/com/dropbox/flow/multicast/Multicaster.kt, multicast/src/test/kotlin/com/dropbox/flow/multicast/ChannelManagerTest.kt, multicast/src/test/kotlin/com/dropbox/flow/multicast/MulticastTest.kt
Fixes #435 
Explanation:
When downstream  flow is  aborted (this is happening when first operator is called on flow -> which is called in Store.fresh extension),  than coroutine context  in which is subflow (created from channel) is cancelling. In this case the channel is cancelled too, but there is no guarantee that channel is properly removed from the channel manager. In the next run when the channel manager is trying to send msg (ChannelManager::doDispatchValue) to this cancelled channel, it throws  AbortFlowException. This exception is caught in StoreRealActor and this caused that all channels(and Multicaster itself) are closed.
=> Remove downstream channel in noncancellable context

.github/workflows/create_swift_package.yml, RELEASING.md
=> Fix workflow

cache/build.gradle.kts, multicast/build.gradle.kts, store/build.gradle.kts
Just adds `iosSimulatorArm64` target to improve KMM support.
Should close #511
=> Add iOS simulator support for KMM projects

cache/build.gradle.kts, multicast/build.gradle.kts
Currently KMM Bridge only supports one module per repo. Removing KMM Bridge plugins from `cache` and `multicast` modules. This means our workflow will only generate a Swift package for `store`. For full context, see: https://kotlinlang.slack.com/archives/CTJB58X7X/p1677961467532679.
=> Remove KMM Bridge From Cache and Multicast

store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/MutableStoreBuilder.kt, store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/StoreBuilder.kt, store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/impl/RealMutableStoreBuilder.kt, store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/impl/RealStoreBuilder.kt, store/src/commonTest/kotlin/org/mobilenativefoundation/store/store5/ClearAllStoreTests.kt, store/src/commonTest/kotlin/org/mobilenativefoundation/store/store5/ClearStoreByKeyTests.kt, store/src/commonTest/kotlin/org/mobilenativefoundation/store/store5/FetcherResponseTests.kt, store/src/commonTest/kotlin/org/mobilenativefoundation/store/store5/FlowStoreTests.kt, store/src/commonTest/kotlin/org/mobilenativefoundation/store/store5/SourceOfTruthErrorsTests.kt, store/src/commonTest/kotlin/org/mobilenativefoundation/store/store5/UpdaterTests.kt
Store5's `StoreBuilder` caused a breaking change. See #532. We can avoid this breaking change by introducing a separate builder for `MutableStore`.
=> Separate MutableStoreBuilder from StoreBuilder

store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/FetcherResult.kt, store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/StoreReadResponse.kt, store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/impl/FetcherController.kt, store/src/commonTest/kotlin/org/mobilenativefoundation/store/store5/FetcherResponseTests.kt
> Hello :spock-hand: ! Does someone have any guidance/sample project on how to handle network/http errors with Store? Currently the network layer in our Android app takes care of catching exceptions, parsing error payloads and returning a custom monad class like Result<NetworkError, T>> . Looking at StoreReadResponse it seems that using Throwable or String is the only way to go. Thanks for your answers!
https://kotlinlang.slack.com/archives/C06007Z01HU/p1699457424194509
=> Support custom error types

store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/StoreBuilder.kt, store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/impl/RealStoreBuilder.kt
Closes #554
This just exposes the `converter` argument in the `RealStoreBuilder` class so that one can provide custom implementations of it. I'd be happy to update the docs as well, if I could be directed to where I can find the sources for them.
This didn't seem to warrant any new tests, but I could add them if desired.
=> Expose converter via StoreBuilder.from() function

core/build.gradle.kts, core/gradle.properties, gradle/libs.versions.toml, paging/build.gradle.kts, paging/gradle.properties, paging/src/commonTest/kotlin/org/mobilenativefoundation/store/paging5/LaunchPagingStoreTests.kt, store/build.gradle.kts
Releasing paging and core
N/A
N/A
=> Release paging and core

paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/PagingSource.kt
Defining `PagingSource`, responsible for loading pages of data from a specific data source, such as a db or network API.
=> Define PagingSource

paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/PagingAction.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/PagingState.kt
- Defining the sealed interfaces `PagingState` and `PagingAction` to represent the current state of the paging data and the actions that can be dispatched to modify the paging state.
=> Define PagingAction and PagingState

paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/Effect.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/Middleware.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/Reducer.kt
- Defining the `Reducer`, `Middleware`, and `Effect` interfaces to handle state reduction, action interception, and side effects.
=> Define Middleware, Reducer, and Effect

paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/MutablePagingBuffer.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/PagingBuffer.kt
- Defining `PagingBuffer` and `MutablePagingBuffer`, a custom data structure for efficiently storing and retrieving paging data.
=> Define PagingBuffer and MutablePagingBuffer

paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/AggregatingStrategy.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/ErrorHandlingStrategy.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/FetchingStrategy.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/PagingConfig.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/PagingItems.kt
- Introducing `PagingConfig`, `InsertionStrategy`, `FetchingStrategy`, `AggregatingStrategy`, `ErrorHandlingStrategy`, and `PagingItems` classes. These open up customization of paging behavior.
=> Define PagingConfig and Paging Strategies

paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/Pager.kt
- Defining `Pager`, the main entry point
=> Define Pager

paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/Logger.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/impl/Constants.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/impl/DefaultLogger.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/impl/Dispatcher.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/impl/EffectsHolder.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/impl/EffectsLauncher.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/impl/Injector.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/impl/OptionalInjector.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/impl/RealDispatcher.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/impl/RealInjector.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/impl/RealOptionalInjector.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/impl/StateManager.kt
- Implementing `RealDispatcher`, `StateManager`, `EffectsLauncher`, `EffectsHolder`, `DefaultLogger`, `RealInjector`, and `RealOptionalInjector` classes
- Defining `Logger`, `Injector`, and `OptionalInjector` interfaces
=> Implement RealDispatcher and Related Classes

paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/impl/RealMutablePagingBuffer.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/mutablePagingBufferOf.kt
- Adding a concrete impl of `MutablePagingBuffer`, a custom data structure for efficiently storing and retrieving paging data.
=> Implement RealMutablePagingBuffer

paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/PagingSourceCollector.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/PagingSourceStreamProvider.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/StorePagingSourceKeyFactory.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/effects.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/impl/DefaultAppLoadEffect.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/impl/DefaultLoadNextEffect.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/impl/DefaultPagingSourceCollector.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/impl/DefaultUserLoadEffect.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/impl/DefaultUserLoadMoreEffect.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/impl/StorePagingSourceStreamProvider.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/store.kt
- Implementing default effects and related Store extension functions and classes
=> Implement Default Effects

paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/DefaultReducerBuilder.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/PagerBuilder.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/impl/DefaultAggregatingStrategy.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/impl/DefaultFetchingStrategy.kt, paging/core/src/commonMain/kotlin/org/mobilenativefoundation/paging/core/impl/DefaultPagingSource.kt
Adding the builders and default paging strategies
=> Add PagerBuilder, DefaultReducerBuilder, and default paging strategies

cache/src/commonMain/kotlin/org/mobilenativefoundation/store/cache5/Cache.kt, cache/src/commonMain/kotlin/org/mobilenativefoundation/store/cache5/LocalCache.kt, cache/src/commonMain/kotlin/org/mobilenativefoundation/store/cache5/StoreMultiCache.kt, cache/src/commonMain/kotlin/org/mobilenativefoundation/store/cache5/StoreMultiCacheAccessor.kt, cache/src/commonTest/kotlin/org/mobilenativefoundation/store/cache5/CacheTests.kt
Adds `getAllPresent()` with no argument to `Cache`, in addition to existing `getAllPresent(keys: List<*>)`.
In the original Guava library there was an [`asMap()`](https://github.com/google/guava/blob/master/guava/src/com/google/common/cache/Cache.java#L178) method which could be used to get the contents of the cache.
Removed `@Ignore` from the `getAllPresent()` test.
Used `clear()` as an inspiration for the implementation.
=> Add Cache.getAllPresent()

tooling/plugins/src/main/kotlin/org/mobilenativefoundation/store/tooling/plugins/AndroidConventionPlugin.kt, tooling/plugins/src/main/kotlin/org/mobilenativefoundation/store/tooling/plugins/KotlinMultiplatformConventionPlugin.kt
Related to #640
Lowers JVM target to 11 as a workaround for https://github.com/Kotlin/dokka/issues/2956
Disabled signing and did a local publish with `gradle publishToMavenLocal` which successfully generated documentation.
Add any other information about the PR here.
=> fix: lower JVM target to Java 11

store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/impl/extensions/store.kt
Closes #668
This PR adds documentation to store.kt so that it's easier to grok all the different types that there are. Along with calling out needing to handle exceptions otherwise there could be potential crashes that are hard to find within your logging.
=> Document extension functions in store.kt

.codecov.yml, .github/workflows/check.yml, .github/workflows/codecov.yml
Modifying our workflow to run codecov on PRs. Bumping min coverage range to 70
N/A
Will chip away at code coverage in separate PRs
=> Run codecov on PR and bump range

cache/build.gradle.kts, core/build.gradle.kts, gradle/libs.versions.toml, store/api/android/store.api, store/api/jvm/store.api, store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/StoreReadResponse.kt, store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/impl/RealStoreBuilder.kt, tooling/plugins/src/main/kotlin/org/mobilenativefoundation/store/tooling/plugins/KotlinMultiplatformConventionPlugin.kt
Closes #644 
All existing unit tests are passing
https://youtrack.jetbrains.com/issue/KT-69534/WasmJs-compilation-fails-with-anonymous-objects-and-exception-throwing-in-when-expressions. Changes to compile:
- Replaced anonymous object with private class `DefaultConverter` (see `RealStoreBuilder.kt`) 
- Refactored `StoreReadResponse.Error.doThrow()` to return `Throwable` (see `StoreReadResponse.kt`)
Updated:
- https://github.com/Kotlin/kotlinx.serialization
- https://github.com/cashapp/turbine
- https://github.com/touchlab/Kermit
- https://github.com/Kotlin/kotlinx-datetime
=> Target WasmJS

store/api/android/store.api, store/api/jvm/store.api, store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/Logger.kt, store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/impl/DefaultLogger.kt, store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/impl/RealMutableStore.kt, store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/internal/concurrent/AnyThread.kt, store/src/commonTest/kotlin/org/mobilenativefoundation/store/store5/mutablestore/RealMutableStoreTest.kt, store/src/commonTest/kotlin/org/mobilenativefoundation/store/store5/mutablestore/util/TestCache.kt, store/src/commonTest/kotlin/org/mobilenativefoundation/store/store5/mutablestore/util/TestConverter.kt, store/src/commonTest/kotlin/org/mobilenativefoundation/store/store5/mutablestore/util/TestFetcher.kt, store/src/commonTest/kotlin/org/mobilenativefoundation/store/store5/mutablestore/util/TestInMemoryBookkeeper.kt, store/src/commonTest/kotlin/org/mobilenativefoundation/store/store5/mutablestore/util/TestLogger.kt, store/src/commonTest/kotlin/org/mobilenativefoundation/store/store5/mutablestore/util/TestSourceOfTruth.kt, store/src/commonTest/kotlin/org/mobilenativefoundation/store/store5/mutablestore/util/TestStore.kt, store/src/commonTest/kotlin/org/mobilenativefoundation/store/store5/mutablestore/util/TestUpdater.kt, store/src/commonTest/kotlin/org/mobilenativefoundation/store/store5/mutablestore/util/TestValidator.kt
Closes #667
Closes #578
This PR is fixing a deadlock in eager conflict resolution. To improve code quality, this PR also:
- Expands on RealMutableStore documentation
- Extracts logging into an internal interface and provides a default implementation to the RealMutableStore
- Introduces internal test utility classes
- Adds RealMutableStore unit tests
=> Fix Eager Conflict Resolution Deadlock and Improve Mutable Store Code Quality
